### ISSUE TITLE
Parser stripping suffix from number

### ISSUE THREAD

**Issue by mikebull** [sebinsua/scrape-twitter#15]
I've noticed that when I scrape a popular Twitter profile with over ten thousand tweets/followers/following/etc, the numbers I get back from the scraper are usually much smaller than they should be.

After a bit of digging, it looks like the counts in parser.js are taking the suffixed value (i.e. 15.5k) and is stripping out non-numerical characters, so 155 is returned instead of 15500. 

Instead of grabbing the suffixed number, do you see any issues with grabbing the data-count attribute, and using that instead? If not, I'll create a PR and send it your way.

**Comment by diego1199** [comment]
Hi @mikebull , can you share your solution for the parser?

**Comment by mikebull** [comment]
@diego1199 I've made the necessary change on a [fork of this repo]https://github.com/mikebull/scrape-twitter).
