### ISSUE TITLE
How to use [EXAMPLE]

### ISSUE THREAD

**Issue by tbhaxor** [sebinsua/scrape-twitter#28]
The documentation lacks the exact usage like [this one](https://github.com/tbhaxor/node-proxifyjs#install-and-use)

Help me

**Comment by zgruza** [comment]
Its simple:
> Git clone
> cd to cloned folder
> python setup.py install
> shell> (for example) scrape-twitter timeline TwitterVideo

**Comment by tbhaxor** [comment]
I am talking about integrating it in python script :man_facepalming:
